# Stage 1: Build the app
FROM node:18.6.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . ./
RUN yarn build

# Stage 2: Serve the app
FROM node:18.6.0-alpine

WORKDIR /app

COPY --from=builder /app/build /app/build

CMD ["npx", "serve", "-s", "build"]
