# Base image
FROM node:18.6.0-alpine

# Set working directory
WORKDIR /app

# Copy package.json and yarn.lock files
COPY ui/package.json .
COPY ui/yarn.lock .

# Install dependencies
RUN yarn install

# Copy the rest of the application code
COPY ui .

# Expose port 3000 for development server
EXPOSE 3000

# Start the development server
CMD ["yarn", "start"]
