version: '3.9'

services:
  backend_service:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - 8000:8000

  frontend_service:
    restart: always
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/ui/node_modules
    depends_on:
      - backend_service

volumes:
  node_modules:
