version: '3.9'

services:
  backend_service:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    networks:
      - gitbook_dev

  frontend_service:
    restart: always
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/ui/node_modules
    depends_on:
      - backend_service
    networks:
      - gitbook_dev

  nginx_sidecar:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    networks:
      - gitbook_dev
    depends_on:
      - backend_service

networks:
  gitbook_dev:

volumes:
  node_modules:
