version: '3.9'

services:
  backend_service:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "8080-8082:8080"
    deploy:
      replicas: 3
      # update_config:
      #   parallelism: 2
      #   delay: 10s
      restart_policy:
        condition: on-failure

  frontend_service:
    restart: always
    container_name: frontend
    build: 
      context: ./ui
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/ui/node_modules
    depends_on:
      - backend_service

networks:
  default:
    name: development

volumes:
  node_modules:
