# Generated by Django 3.2.15 on 2022-11-03 18:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221103_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('74c40a9e-5ba6-11ed-9da8-7f94e8bff6aa'), primary_key=True, serialize=False),
        ),
    ]
