# Generated by Django 3.2.15 on 2022-11-03 19:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.UUIDField(default=uuid.UUID('d38f7310-5bab-11ed-9da8-7f94e8bff6aa'), primary_key=True, serialize=False),
        ),
    ]
