# Generated by Django 3.2.15 on 2022-11-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221103_1915'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
