# Generated by Django 3.2.15 on 2022-12-06 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedCard',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=100)),
                ('project_drescriptions', models.TextField(max_length=5000)),
                ('repository', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
