# Generated by Django 3.2.15 on 2023-03-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feedcard_card_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedcard',
            name='pinned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='feedcard',
            name='tags',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
