FROM python:3.8.13-slim-buster

WORKDIR /usr/src/app

# Copy the source code and requirements file
COPY . .

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc musl-dev && \
    rm -rf /var/lib/apt/lists/*

# Create a virtual environment and install project dependencies
RUN python -m venv /venv && \
    /venv/bin/pip install --no-cache-dir --upgrade pip && \
    /venv/bin/pip install --no-cache-dir -r requirements.txt

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Start the application
CMD ["/venv/bin/python", "app.py"]
